name: fairseq
on: [workflow_dispatch]
jobs:
  build:
    name: Build fairseq
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12','3.13']
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install torch and echo version
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cu126
          python -c "import torch; print(torch.__version__)"
      - name: pip wheel fairseq with pip<24.1
        run: | 
          python -m pip install --upgrade "pip<24.1"
          pip wheel fairseq
      - uses: actions/upload-artifact@v4
        with:
          name: Windows whl
          path: fairseq-*.whl
          if-no-files-found: error
