name: fairseq
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    name: Build fairseq
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: | 
          python -m pip install --upgrade "pip<24.1"
          pip install fairseq
      - run: |
          python -c "import torch; print(f'Using torch version: {torch.__version__}')"
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: Windows whl
          path: fairseq-*.whl
          if-no-files-found: error
