name: fairseq
on: 
  workflow_dispatch:
  push:
    branches:
      - fairseq
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build fairseq
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12','3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install torch and echo version
        run: |
          pip install uv
          uv pip install torch --index-url https://download.pytorch.org/whl/cu126 --system
          python -c "import torch; print(torch.__version__)"
      - name: Build fairseq wheel
        run: |
          pip install --upgrade "pip<24.1" 
          pip wheel fairseq
      - uses: actions/upload-artifact@v4
        with:
          name: fairseq-py${{ matrix.python-version }}-win
          path: fairseq-*.whl
          if-no-files-found: error
