name: fairseq
on:
  workflow_dispatch:
  push:
    branches:
      - fairseq
    tags:
      - 'v*' # 例如 v0.12.2, v1.0.0 等标签会触发
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build fairseq wheel
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    outputs:
      version_number: ${{ steps.release_info.outputs.version_number }}
      torch_build_info: ${{ steps.release_info.outputs.torch_build_info }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Build fairseq wheel
        run: |
          python -m pip install --upgrade "pip<24.1" 
          pip install uv 
          uv pip install fairseq --system
          pip wheel fairseq --no-deps --wheel-dir=.
      - name: Get release info
        id: release_info
        shell: bash
        run: |
          # 获取当前安装的 fairseq 版本
          FAIRSEQ_VERSION=$(python -c "import fairseq; print(fairseq.__version__)" || echo "unknown")
          # 获取当前安装的 torch 版本信息
          TORCH_BUILD_INFO=$(python -c "import torch; print(torch.__version__ )" || echo "unknown")
          # 设置输出变量
          echo "version_number=${FAIRSEQ_VERSION}" >> $GITHUB_OUTPUT
          echo "torch_build_info=${TORCH_BUILD_INFO}" >> $GITHUB_OUTPUT
          # 设置环境变量以供后续作业使用
          echo FAIRSEQ_VERSION=$FAIRSEQ_VERSION
          echo TORCH_BUILD_INFO=$TORCH_BUILD_INFO


      - uses: actions/upload-artifact@v4
        with:
          name: fairseq-py${{ matrix.python-version }}-win
          path: fairseq-*.whl
          if-no-files-found: error

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest # 通常在 Linux 环境中创建 Release 更方便
    needs: build # 依赖 build 作业成功完成
    # 仅在推送标签或手动调度并提供了版本时运行
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write # 创建 Release 和上传资产所必需的权限
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files (for debugging)
        run: ls -R 

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fairseq-${{ needs.build.outputs.version_number }}
          name: Build fairseq
          body: |
            **fairseq ${{ needs.build.outputs.version_number }}** build with ${{ needs.build.outputs.torch_build_info }} in windows

            Download and install via:
            ```sh
            python -m pip install --upgrade "pip<24.1"
            # 请从下面的资产中选择适合您 Python 版本的 .whl 文件。
            # Python 3.10 示例 (fairseq 版本 ${{ needs.build.outputs.version_number }}):
            pip install fairseq-${{ needs.build.outputs.version_number }}-cp310-cp310-win_amd64.whl
            ```
          files: "**/fairseq-*.whl"
          draft: true # 设置为 true 以创建草稿版本，稍后手动发布
          prerelease: false # 设置为 true 以标记为预发布版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
